name: "Build"
on:
  push:
    tags:
    - '*'
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Get the tag
      shell: powershell
      id: get_tag
      run: |
        "name=TAG::$($env:GITHUB_REF.replace('refs/tags/',''))" >> $env:GITHUB_OUTPUT
    - name: "Checkout sources"
      uses: actions/checkout@v5
      with:
        submodules: 'true'
    - name: Copy vcpkg/CMake presets into ledger
      shell: pwsh
      run: |
        Copy-Item -Path "vcpkg.json","CMakePresets.json" -Destination "ledger"
    - name: "Run build script"
      shell: powershell
      run: |
        .\build.ps1
    - name: "Create release archive"
      shell: powershell
      run: |
        7z a "ledger-$env:TAG.zip" .\ledger\Release\ledger.exe
      env:
        TAG: ${{ steps.get_tag.outputs.TAG }}
    - name: "Create Release"
      uses: softprops/action-gh-release@v2
      with:
        files: ledger-${{ steps.get_tag.outputs.TAG }}.zip
